// Copied from downstream-mobile (same Firebase project: downstream-181e2).
// File generated by FlutterFire CLI; do not hand-edit casually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with the familiars Firebase apps.
///
/// Familiars piggybacks on the `downstream-181e2` Firebase project (same
/// identity surface), and on the iOS/Android app entries already registered
/// for the downstream-mobile bundle / package id.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnDtyPohW9oh2_NjcjV_lN2RqOume04t4',
    appId: '1:482686216746:android:220ff777bdd7bfbb6e3153',
    messagingSenderId: '482686216746',
    projectId: 'downstream-181e2',
    storageBucket: 'downstream-181e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgVnzb9YMpJnE2JQxEuJuWmTydbFhinc',
    appId: '1:482686216746:ios:f48b3b40198638c56e3153',
    messagingSenderId: '482686216746',
    projectId: 'downstream-181e2',
    storageBucket: 'downstream-181e2.firebasestorage.app',
    androidClientId:
        '482686216746-8u7dhvb7dp3chhq80tofq2cjdcilpmni.apps.googleusercontent.com',
    iosClientId:
        '482686216746-uem247orm26i3kqiedrvhv5k7huopevq.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.downstream.monitor',
  );
}
